name: Update README

on:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          template: "README.tpl"
          writeTo: "README.md"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update generated README"
          author_name: "readme-scribe 🤖"
          author_email: "actions@github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
